// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnjyYfD_ooMPbRwxbrzvQwddZuDXe349I',
    appId: '1:18141359679:web:7cb520b73faa2c9acc528a',
    messagingSenderId: '18141359679',
    projectId: 'tesis-intesud',
    authDomain: 'tesis-intesud.firebaseapp.com',
    storageBucket: 'tesis-intesud.firebasestorage.app',
    measurementId: 'G-K10PT9829M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYI8bG6ZrzRUnoEZiSIxOR2ndy6eyKBTM',
    appId: '1:18141359679:android:395b40a340b236dfcc528a',
    messagingSenderId: '18141359679',
    projectId: 'tesis-intesud',
    storageBucket: 'tesis-intesud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gkJ_DSqEovyGyTPJqxi--9VXGZ4qpK4',
    appId: '1:18141359679:ios:53910b469d41616ecc528a',
    messagingSenderId: '18141359679',
    projectId: 'tesis-intesud',
    storageBucket: 'tesis-intesud.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2gkJ_DSqEovyGyTPJqxi--9VXGZ4qpK4',
    appId: '1:18141359679:ios:53910b469d41616ecc528a',
    messagingSenderId: '18141359679',
    projectId: 'tesis-intesud',
    storageBucket: 'tesis-intesud.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnjyYfD_ooMPbRwxbrzvQwddZuDXe349I',
    appId: '1:18141359679:web:c9814998c682e7dbcc528a',
    messagingSenderId: '18141359679',
    projectId: 'tesis-intesud',
    authDomain: 'tesis-intesud.firebaseapp.com',
    storageBucket: 'tesis-intesud.firebasestorage.app',
    measurementId: 'G-3WF65VDD9R',
  );
}
